# Generated by Django 5.2.3 on 2025-06-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.URLField(max_length=2048, verbose_name='thumbnail image url'),
        ),
    ]
