# Generated by Django 5.2.3 on 2025-06-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_recipe_id_alter_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='id',
            field=models.IntegerField(default=123, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
