# Generated by Django 5.2.3 on 2025-09-09 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('img', models.URLField(max_length=2048, verbose_name='thumbnail image url')),
                ('title', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('time', models.CharField(max_length=25)),
                ('servings', models.PositiveIntegerField()),
                ('url', models.URLField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipe_id', 'user')},
            },
        ),
    ]
