# Generated by Django 4.2.23 on 2025-06-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_rating_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.URLField(verbose_name='thumbnail image url'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(),
        ),
    ]
